import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0, 10, 100)
y1 = np.sin(x)
y2 = np.cos(x)
y3 = x**2
y4 = np.sqrt(x)
plt.figure(figsize=(10, 8))
plt.subplot(2, 2, 1)
plt.plot(x, y1, label="y = sin(x)", color="blue")
plt.title("Sine Wave")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.subplot(2, 2, 2)
plt.plot(x, y2, label="y = cos(x)", color="green")
plt.title("Cosine Wave")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.subplot(2, 2, 3)
plt.plot(x, y3, label="y = x^2", color="red")
plt.title("Quadratic Function")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.subplot(2, 2, 4)
plt.plot(x, y4, label="y = √x", color="purple")
plt.title("Square Root Function")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.tight_layout()
plt.show()
